services:
  ui-tests:
    build:
      context: ./portal-ui-tests
    volumes:
      - ./ui-reports:/results
  api-tests:
    build:
      context: ./portal-api-tests
    volumes:
      - ./api-reports:/results
