services:
  ui-tests:
    build:
      context: ./portal-ui-tests
    env_file:
      - .env
    volumes:
      - ./ui-reports:/app/cypress/results
  api-tests:
    build:
      context: ./api-tests
    env_file:
      - .env
    volumes:
      - ./api-reports:/results
